// PersonList
export const FETCHING_PERSON_LIST = 'START_FETCHING_PERSON_LIST'
export const REFRESHING_PERSON_LIST = 'REFRESHING_PERSON_LIST'
export const FILTER_PERSON_LIST = 'FILTER_PERSON_LIST'
export const CLEAR_FILTER_PERSON_LIST = 'CLEAR_FILTER_PERSON_LIST'

// Location
export const SET_LOCATION = 'SET_LOCATION'

// PersonDetail
export const ON_PERSON_SELECTED = 'ON_PERSON_SELECTED'
export const REFRESHING_PERSON_DETAIL = 'REFRESHING_PERSON_DETAIL'

// PersonCreate
export const CREATING_NEW_PERSON = 'CREATING_NEW_PERSON'
export const CLEAN_PERSON_CREATE_RESPONSE = 'CLEAN_PERSON_CREATE_RESPONSE'

// Api calls
export const ERROR_FETCHING = 'ERROR_FETCHING_PERSON_LIST'
export const SUCCESS_FETCHING = 'SUCCESS_FETCHING_PERSON_LIST'
export const SUCCESS_REFRESHING = 'SUCCESS_REFRESHING'
export const ERROR_REFRESHING = 'ERROR_REFRESHING'
export const SUCCESS_REFRESHING_PERSON = 'SUCCESS_REFRESHING_PERSON'
export const ERROR_REFRESHING_PERSON = 'ERROR_REFRESHING_PERSON'
export const SUCCESS_CREATING_NEW_PERSON = 'SUCCESS_CREATING_NEW_PERSON'
export const ERROR_CREATING_NEW_PERSON = 'ERROR_CREATING_NEW_PERSON'
