// PersonList
export const FETCHING_PERSON_LIST = 'START_FETCHING_PERSON_LIST'
export const REFRESHING_PERSON_LIST = 'REFRESHING_PERSON_LIST'
export const FILTER_PERSON_LIST = 'FILTER_PERSON_LIST'
export const CLEAR_FILTER_PERSON_LIST = 'CLEAR_FILTER_PERSON_LIST'

// Location
export const SET_LOCATION = 'SET_LOCATION'

// Api calls
export const ERROR_FETCHING = 'ERROR_FETCHING_PERSON_LIST'
export const SUCCESS_FETCHING = 'SUCCESS_FETCHING_PERSON_LIST'
export const SUCCESS_REFRESHING = 'SUCCESS_REFRESHING'
export const ERROR_REFRESHING = 'ERROR_REFRESHING'
