const tintColor = '#29235C'

export default {
  tintColor,
  tabIconDefault:                       '#a7aaaa',
  tabIconSelected:                      'rgba(41, 35, 92, .85)',
  tabBar:                               '#fefefe',
  errorBackground:                      '#e25a36',
  successBackground:                    '#1ae979',
  darkRed:                              '#a20737',
  errorText:                            '#fff',
  warningBackground:                    '#EAEB5E',
  warningText:                          '#666804',
  noticeBackground:                     '#29235C',
  noticeText:                           '#fff',
  white:                                '#fff',
  gray:                                 '#b9bdbd',
  gray2:                                '#86939e',
  grey3:                                '#f7f7f7',
  grey4:                                '#d7d7d7',
  grey5:                                '#eeeeee',
  grey6:                                '#c7c7c7',
  grey7:                                '#43484d',
  darkGrey:                             '#444242',
  background:                           '#eef0f3',
  transparent:                          'rgba(0, 0, 0, 0)',
  searchHomeBackground:                 'rgba(181, 182, 180, .4)',
  tabNavigationBackground:              '#f9f9f9',
  tabNavigationBorder:                  'rgba(157, 161, 161, .3)',
}
